services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=production
    restart: always
    networks:
      - stoobit-demo-network

networks:
  stoobit-demo-network:
    driver: bridge